### ISSUE TITLE
How to make spylon work with Spark 3.0.0 with scala 2.12?

### ISSUE THREAD

**Issue by calebshei** [Valassis-Digital-Media/spylon#54]
We would like to have spylon to work with Spark 3.0.0 with scala 2.12. 
Can anyone please outline the things that need to be changed or enhanced in order for it to work?

**Comment by mariusvniekerk** [comment]
Given that a lot more of the spark configuration can just be done in pyspark without spylon now than when this was originally written this might not even really be needed at all anymore

**Comment by calebshei** [comment]
Thanks Marius! The problem that I'm encountering is found not to be related to spylon, which in fact doesn't tie to any particular scala version. It is because the python platform toolkit that preloads a scala 2.11 toolkit jar stops me from loading a scala 2.12 toolkit jar.
